version: "3"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'todolist'
      MYSQL_ROOT_PASSWORD: '123123'
    volumes:
#      - ./.docker/mysql/my.cnf:/etc/my.cnf
      - ./.docker/volumes/mysql_services:/var/lib/mysql

  nest:
    build: .docker/nest
    command: /run.sh
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./nest/:/var/www/
      - ./.docker/nest/run.sh:/run.sh

  react:
    build: .docker/react
    command: /run.sh
    volumes:
      - ./react/:/var/www/
      - ./.docker/react/run.sh:/run.sh

  nginx:
    image: nginx:1.15.12
    command: nginx
    depends_on:
      - nest
      - react
    links:
      - nest
      - react
    volumes:
      - ./react/public:/var/www/public
      - ./nest/public:/var/www/public/backend/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
